name: 'Terraform Landing Zone Deployment'

on:
  push:
    branches: [ main ]
    paths:
      - 'landingzone-test/**'
      - ".github/workflows/terraform_test_lz.yaml"
  pull_request:
    paths:
      - 'landingzone-test/**'
      - ".github/workflows/terraform_test_lz.yaml"

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TEST }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET_TEST }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_TEST }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID_TEST }}
    defaults:
      run:
        working-directory: ./landingzone-test
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform plan -no-color -out=plan.out

  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: test   # ðŸ‘ˆ reviewers enforced here
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    defaults:
      run:
        working-directory: ./landingzone-test
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
      - run: terraform apply -auto-approve